### ISSUE TITLE
new entitiy ogit/Device

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#172]
Hi Peter,
could you please create the entity ogit/Device according to what we reviewed?

Descr: Any type of device

Optional attributes:
ogit/id
ogit/name
ogit/purchaseDate
ogit/Datacenter/moveProductionDate
ogit/endOfWarranty
ogit/powerConsumption

**Comment by conofre** [comment]
For attributes: see our attributes sheet for the moveProductionDate, purchaseDate, endOfWarranty, powerConsumption
New attribute: ogit/id - General id

**Comment by plarem** [comment]
While ogit/Device will be a general entity, I would prefer to have only ogit/id and ogit/name as optional attributes. ogit/purchaseDate, ogit/Datacenter/moveProductionDate, ogit/endOfWarranty and ogit/powerConsumption is more datacenter stuff and they will be optional when they are often used in global graphit. Since that I would leave it.

**Comment by plarem** [comment]
done
